# Second stage for the Lambda function
ARG LAMBDA_PLATFORM=linux/amd64
FROM --platform=${LAMBDA_PLATFORM} public.ecr.aws/lambda/python:3.11

# ENV ASTROLOGY_CHART_BUCKET='amplify-d2cbfkrtv7urrr-amplif-inseenbucket909b8387-advki4vx1trx'

# Use the latest stable upstream package on this test branch.
RUN pip install --no-cache-dir -t ${LAMBDA_TASK_ROOT} \
    kerykeion==5.12.9 \
    boto3==1.35.76

# Copy your Lambda function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Command for the Lambda function
CMD [ "lambda_function.handler" ]
